title: "Wizards vs Trolls"
description: A reimagining of the popular game Plants vs Zombies
remote_theme: just-the-docs/just-the-docs@v0.10.0
search_enabled: true
color_scheme: light
nav_enabled: true

nav_external_links:
  - title: Repository on GitHub
    url: https://github.com/giacomofoschii/PPS-24-WvT

mermaid:
  version: "9.1.3"

custom_css:
  - assets/css/custom.css